/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.heylyn.exception.ResultException;
import com.heylyn.network.HttpUtil;
import com.heylyn.result.OnResultCallback;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    /*
    @Test public void Heylyn() {
    	HttpUtil.request("https://www.baidu.com/", new OnResultCallback() {

			@Override
			public void success(Object obj, String msg) {
				// TODO Auto-generated method stub
				System.out.println(obj.toString());
			}

			@Override
			public void failure(ResultException e) {
				// TODO Auto-generated method stub
				System.out.println(e.getMessage().toString());
			}});
    }*/
}
