/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.heylyn.exception.ResultException;
import com.heylyn.network.HttpClient;
import com.heylyn.network.ResultResponse;
import com.heylyn.network.ResultResponseCallback;


import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void Heylyn() {
    	HttpClient.get("https://www.baidu.com/", new ResultResponseCallback() {

			@Override
			public void success(ResultResponse res, String msg) {
				// TODO Auto-generated method stub
				System.out.println(res.body.toString()+" "+res.code.toString());
				System.out.println(msg);
			}

			@Override
			public void failure(ResultException e) {
				// TODO Auto-generated method stub
				
			}});
    }
}
