/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.heylyn.exception.ResultException;
import com.heylyn.jackson.JacksonUtil;
import com.heylyn.network.HttpClient;
import com.heylyn.network.ResultCallback;
import com.heylyn.network.ResultResponse;
import com.heylyn.network.ResultResponseCallback;
import com.heylyn.network.download.DownloadUtil;
import com.heylyn.network.download.ProgressCallback;

import okhttp3.OkHttpClient;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void Heylyn() {

    	System.out.println("Heylyn run ...");
   
    	
    	try {
   		 TimeUnit.DAYS.sleep(1);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    
    }
}
